### ISSUE TITLE
Allow certain exception to have stack traces in logs

### ISSUE THREAD

**Issue by JulioDeLeon** [HotelsDotCom/styx#413] opened 2019-05-16 18:12 UTC
## The problem
Currently, we are experiencing exceptions being logged without a stack trace. These exceptions are unrelated to origins being unreachable/timining out.

 ## Detailed description
 While running stress tests, Styx started showing `java.lang.ArithmeticException: null` within our logs. Currently, this is by design as shown here: 
https://github.com/HotelsDotCom/styx/blob/master/components/proxy/src/main/java/com/hotels/styx/proxy/HttpErrorStatusCauseLogger.java#L37

## Acceptance criteria

- A developer should be able configure which exceptions are allowed to print a stack trace.

**Comment by mikkokar** [comment] 2019-05-17 07:22
Hi @JulioDeLeon. This sounds reasonable.

**Comment by kvosper** [comment] 2019-05-17 08:46
@JulioDeLeon we only avoid stack traces when the status code is > 500, e.g. 502 Bad Gateway, 504 Gateway Timeout, etc. These are special cases that cannot be caused by arbitrary exceptions such as `ArithmeticException`.

The lack of stack trace on `ArithmeticException` is inherent Java behaviour: https://docs.oracle.com/javase/8/docs/api/?java/lang/ArithmeticException.html

> ArithmeticException objects may be constructed by the virtual machine as if suppression were disabled and/or the stack trace was not writable.

**Comment by kvosper** [comment] 2019-05-17 08:48
Furthermore, I would argue that there is no need to log stack traces for Bad Gateway, etc. as the exceptions are merely the way that Styx is internally communicating this information, and not indicative of any programming bug.

For this reason I am closing the issue for now. Please comment if there is any misunderstanding.

**Closed by kvosper** 2019-05-17 08:48 UTC
